### PR TITLE
Architectural Design

### PR DESCRIPTION
**Pull request by mkgrey5921**
Feel free to add more to it if you like. If you would like for me to make any changes on what's currently provided, please let me know so I can makes the changes since I built the design in a separate program. Thank you.

### CODE REVIEW

**Comment by scottmhogan** [comment]
Looks good!

**Comment by Nick-AI** [comment]
Looks great!
What program did you use to create it?

**Comment by IsaiasCuevas** [comment]
I think the only thing that i spotted missing on the architectural design is some way to export the data into the MySQL database. What do you all think?

**Review by igree2737 — APPROVED** [review]
Looks good to me!

**Pull request merged**
